import img from "./assets/img.jpg"

export const ProductsData = [
    {
        id: 1,
        isAddedToCart: false,
        title: "Fancy Product",
        img: img,
        price: 40.00,
        comparePrice: 80.00,
        onSale: false,

    },
    {
        id: 2,
        isAddedToCart: false,
        title: "Special Item",
        img: img,
        price: 18.00,
        comparePrice: 20.00,
        onSale: false,
    },
    {
        id: 3,
        isAddedToCart: false,
        title: "Sale Item",
        img: img,
        price: 25.00,
        comparePrice: 50.00,
        onSale: true,
    },
    {
        id: 4,
        isAddedToCart: false,
        title: "Popular Item",
        img: img,
        price: 40.00,
        comparePrice: 80.00,
        onSale: false,
    },
    {
        id: 5,
        isAddedToCart: false,
        title: "Sale Item",
        img: img,
        price: 25.00,
        comparePrice: 50.00,
        onSale: true,
    },
    {
        id: 6,
        isAddedToCart: false,
        title: "Fancy Product",
        img: img,
        price: 140.00,
        comparePrice: 280.00,
        onSale: true,
    },
    {
        id: 7,
        isAddedToCart: false,
        title: "Special Item",
        img: img,
        price: 40.00,
        comparePrice: 80.00,
        onSale: false,
    },
    {
        id: 8,
        isAddedToCart: false,
        title: "Popular Item",
        img: img,
        price: 18.00,
        comparePrice: 30.00,
        onSale: true,
    },
]